language: android
android:
components:
- tools
- platform-tools
- build-tools-23.0.1
- android-23
- extra-android-support
- extra-android-m2repository
sudo: required
jdk:
- oraclejdk8
- wget http://services.gradle.org/distributions/gradle-2.4-bin.zip
- unzip gradle-2.4-bin.zip
- export GRADLE_HOME=$PWD/gradle-2.4
- export PATH=$GRADLE_HOME/bin:$PATH
install: true
# before_script:
# - chmod +x gradlew
script: "./gradlew assembleRelease --stacktrace"
branches:
only:
- master
