language: android
android:
components:
- platform-tools
- build-tools-23.0.1
- android-25
- extra-android-m2repository
before_script:
- chmod +x gradlew
script:
- ./gradlew build
branches:
only:
- master
