language: android
android:
components:
- tools
- platform-tools
- build-tools-23.0.1
- android-23
- extra-android-support
- extra-android-m2repository
sudo: required
jdk:
- oraclejdk8
install: true
before_script:
- chmod +x gradlew
script:
- ./gradlew assembleRelease --stacktrace
branches:
only:
- master
